### ISSUE TITLE
Exit with <> 0 when any test failed

### ISSUE THREAD

**Issue by honzabrecka** [mfikes/tach#2]
Would be great to exit with non zero status code when any test failed. It's useful when running on CI for example.

**Comment by mfikes** [comment]
I agree. I suppose we could take the exit value of Planck or Lumo and ensure it is propagated to be the exit value of the plugin (assuming that's possible). 

If so, then it is possible (with Planck at least) to check the results of the test and exit appropriately. For example, Planck does this in its own unit tests itself here: https://github.com/mfikes/planck/blob/b56ade638d6ac375fb5c3231d80de0d30b2f8935/script/test-unit#L7-L9

**Comment by honzabrecka** [comment]
I thought about the same approach, but without the need to have this multimethod implemented in my code. Inject it somehow automagically. But for the start, the note in README would be sufficient.

**Comment by mfikes** [comment]
Perhaps it could be injected by passing an additional `-e` prior to the `-e` that runs the test runner which evaluates a little code to set up the multimethod. The injected code could be Planck and Lumo specific, causing either to exit as needed (assuming that on Lumo's side there is some Node call that causes it to exit with a given exit code).

Whether or not to inject this multimethod could also be driven by some `project.clj`, perhaps something like (with a better name):

```
{:tach {:inject-exit-code? true}}
```

**Comment by honzabrecka** [comment]
Yes, I really like this solution. Lumo can be exited with `(.exit js/process status)`.

**Comment by anmonteiro** [comment]
Lumo still doesn't exit with a value different than 0 when tests fail. this is the blocking issue: https://github.com/anmonteiro/lumo/issues/58
